# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: clinical-information-sharing
canonical: http://jpfhir.jp/fhir/clins
name: "電子カルテ情報共有サービスFHIR実装ガイド"
title: "電子カルテ情報共有サービスFHIR実装ガイド JP-CLINS（CLinical Information Sharing ImplementationGuide）"
description: "電子カルテ情報共有サービスFHIR実装ガイド JP-CLINS ImplementationGuide"
status: draft # draft | active | retired | unknown 
version: 0.9.3
date: 2023-10-25
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2023+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC BY-ND  #  https://www.hl7.org/fhir/valueset-spdx-license.html
# https://www.hl7.org/fhir/valueset-jurisdiction.html 
publisher:
  name: Kazuhiko Ohe@JAMI/HL7Japan,JAMI, and The University of Tokyo
  url: http://jpfhir.jp
  email: office@hlfhir.jp
copyright: Copyright (temporaly) by Kazuhiko Ohe@The University of Tokyo, CC(Creative Commons license) BY-ND CC表示・改変禁止
jurisdiction: 'urn:iso:std:iso:3166-2#JP'
dependencies:
  jp-core.r4:
# to avoid warning message "The canonical URL for an Implementation Guide must point directly to the implementation guide resource, not to the Implementation Guide as a whole"
    uri: http://jpfhir.jp/fhir/core/ImplementationGuide/jp-core.r4
    version: 1.1.2-dev
  jpfhir-terminology:
    uri: http://jpfhir.jp/fhir/jpfhir-terminology/
    version: 1.1.1
#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: 名称：電子カルテ情報共有サービスFHIR仕様  　JP-CLINS
  core6spec.md:
    title: 名称：６情報送信仕様
  
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
    ６情報送信仕様: core6spec.html
    プロファイル: artifacts.html
    改訂履歴: history.html
  Artifacts: 
    Artifacts: artifacts.html
    
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'
  no-narrative: 
    - CodeSystem/*
  active-tables: 'false'
  apply-version: 'true'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  display-warnings: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'true'
#  excludeexample: 'false'
  generate: #what does this do - todo: remove and see
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_AllergyIntolerance_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Binary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Condition_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Consent_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Consent
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Device_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Device
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DeviceUseStatement_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DeviceUseStatement
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DocumentReference_CDAdocument
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DocumentReference_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DocumentReference
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Encounter_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ImagingStudy_Radiology_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Immunization_eClinicalSummary
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_MedicationRequest_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_MedicationStatement_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationStatement
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Observation_LabResult_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Observation_Common_eClinicalSummary
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Patient_eCS
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Patient_eCS
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Practitioner_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Procedure_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_RelatedPerson_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_RelatedPerson
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_ResearchStudy_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchStudy
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_ResearchSubject_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchSubject
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ServiceRequest
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Specimen
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDosage_eCS
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP__eCS_Department
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP_eCS_InstitutionNumber
    - http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DispenseRequest_InstructionForDispense
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/jlac10-specimen-codes
    - http://jpfhir.jp/fhir/CodeSystem/JP-CLINS-ObsLabResult-CoreLabo-CS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_ObservationLabResultLocalUncoded_CS
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_CLINS_ObsLabResult_Uncoded_CS
    - http://jpfhir.jp/fhir/Common/CodeSystem/doc-typecodes
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/prescription-section
    - http://jpfhir.jp/fhir/core/CodeSystem/practitioner-certificate-category
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/prescription-category
    - urn:oid:1.2.392.200250.2.2.2
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_ehrshrs_indication
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicalLicenseCertificate_CS
    - http://jpfhir.jp/fhir/eClinicalSummary/CodeSystem/observation-subcategory-cs
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_SimpleObservationCategory_CS
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jami-ePreDispenseInstruction
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jami-ePreOrderUsageCode
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-abo-bld_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-alb_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-alp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-alt_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-amy_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-aptt_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ast_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-bnp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-bs_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-bun_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ca_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-che_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ck_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-cl_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-cre_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-crp-class_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-crp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-cys-c_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-d-bil_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-dd_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-fbs_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ggt_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-hb_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-hdl-c_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-plt_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-k_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ld_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ldl-c_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-na_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-hba1c-ngsp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-nt-probnp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-pt-act_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-pt-inr_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-pt-ratio_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-pt-sec_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-rbc_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-rh-bld_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-t-bil_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-t-cho_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-tg_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-tp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-u-a/c_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-u-bld_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-u-glu_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-u-p/c_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-u-tp_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-ua_VS
    - http://jpfhir.jp/fhir/ValueSet/JP-CLINS-ObsLabResult-CoreLabo-wbc_VS
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-gs1-14
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-hot9
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-yj
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/mhlw-drugCode-generalNameCode
    - http://jpfhir.jp/fhir/Common/ValueSet/mhlw-ePreCDA-insuranceCategory
