# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: clinical-information-sharing
canonical: http://jpfhir.jp/fhir/clincs
name: "電子カルテ情報共有サービスFHIR実装ガイド"
title: "電子カルテ情報共有サービスFHIR実装ガイド JP-CLINS（CLinical Information Sharing ImplementationGuide）"
description: "電子カルテ情報共有サービスFHIR実装ガイド JP-CLINS ImplementationGuide"
status: draft # draft | active | retired | unknown 
version: 0.9.2
date: 2023-09-25
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2022+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC BY-ND  #  https://www.hl7.org/fhir/valueset-spdx-license.html
# https://www.hl7.org/fhir/valueset-jurisdiction.html 
publisher:
  name: Kazuhiko Ohe@JAMI/HL7Japan and The University of Tokyo
  url: http://jpfhir.jp
  email: office@hlfhir.jp
copyright: Copyright Kazuhiko Ohe@The University of Tokyo, CC(Creative Commons license) BY-ND CC表示・改変禁止
jurisdiction: 'urn:iso:std:iso:3166-2#JP'
dependencies:
  jp-core.r4:
# to avoid warning message "The canonical URL for an Implementation Guide must point directly to the implementation guide resource, not to the Implementation Guide as a whole"
    uri: http://jpfhir.jp/fhir/core/ImplementationGuide/jp-core.r4
    version: 1.1.2-dev
  jpfhir-terminology:
    uri: http://jpfhir.jp/fhir/jpfhir-terminology/
    version: 1.1.1
    
#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: 名称：電子カルテ情報共有サービスFHIR仕様  　JP-CLINS
  core6spec.md:
    title: 名称：６情報送信仕様
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
    ６情報送信仕様: core6spec.html
    プロファイル: artifacts.html
  Artifacts: 
    Artifacts: artifacts.html
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'
  no-narrative: 
    - CodeSystem/*
  active-tables: 'false'
  apply-version: 'true'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  display-warnings: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'true'
#  excludeexample: 'false'
  generate: #what does this do - todo: remove and see
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_AllergyIntolerance_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Binary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_CarePlan_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_CarePlan
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Condition_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Consent_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Consent
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Coverage_eCS_insurance
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Coverage_eCS_publicPayment
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Device_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Device
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DeviceUseStatement_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DeviceUseStatement
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DocumentReference_CDAdocument
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_DocumentReference_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DocumentReference
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Encounter_OW_eCS_Contained
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Encounter_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_FamilyMemberHistory_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ImagingStudy_Radiology_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Immunization_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Immunization
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_MedicationRequest_ePrescriptionData_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_MedicationStatement_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationStatement
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Observation_LabResult_eCS_Contained
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Observation_LabResult_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Observation_Common_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Organization_eCS_Contained
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Organization_eCS_coveragePayer
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Organization_eClinicalSummary_department_Contained
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Organization_eClinicalSummary_department
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Organization_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Patient_eCS_Contained
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Patient_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Practitioner_eCS_Contained
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Practitioner_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Practitioner_eClinicalSummary_author
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_PractitionerRole_eClinicalSummary_author
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Procedure_eClinicalSummary
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_RelatedPerson_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_RelatedPerson
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_ResearchStudy_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchStudy
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_ResearchSubject_eClinicalSummary
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchSubject
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_ServiceRequest_eCS_Contained
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ServiceRequest
    - http://jpfhir.jp/fhir/eClinicalSummary/StructureDefinition/JP_Specimen_eCS_Contained
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Specimen
    - http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DispenseRequest_InstructionForDispense
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/jlac10-specimen-codes
    - urn:oid:1.2.392.200250.2.2.20.30
    - urn:oid:1.2.392.200250.2.2.20.40
    - urn:oid:1.2.392.200250.2.2.30.10
    - urn:oid:1.2.392.200250.2.2.20.22
    - urn:oid:1.2.392.200250.2.2.20.32
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/route-codes
    - http://jpfhir.jp/fhir/eClinicalSummary/CodeSystem/JP_CLINS_ObsLabResult_JLAC10Unmethod_CS
    - http://jpfhir.jp/fhir/eClinicalSummary/ValueSet/JP_ObservationLabResultLocalUncoded_CS
    - http://jpfhir.jp/fhir/eClinicalSummary/CodeSystem/JP_CLINS_ObsLabResult_Uncoded_CS
    - http://jpfhir.jp/fhir/Common/CodeSystem/doc-typecodes
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/communication-category
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/prescription-section
    - urn:oid:1.2.392.100495.20.3.61
    - http://jpfhir.jp/fhir/core/CodeSystem/practitioner-certificate-category
    - http://jpfhir.jp/fhir/Common/CodeSystem/practitioner-role-category
    - urn:oid:1.2.392.100495.20.3.21
    - http://jpfhir.jp/fhir/ePrescription/CodeSystem/prescription-category
    - urn:oid:1.2.392.100495.20.3.71
    - urn:oid:1.2.392.200250.2.2.2
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_ehrshrs_indication
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicalLicenseCertificate_CS
    - http://jpfhir.jp/fhir/eClinicalSummary/CodeSystem/observation-subcategory-cs
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_SimpleObservationCategory_CS
    - urn:oid:1.2.392.100495.20.3.22
    - urn:oid:1.2.392.100495.20.1.23
    - urn:oid:1.2.392.100495.20.2.101
    - urn:oid:1.2.392.100495.20.2.51
    - urn:oid:1.2.392.100495.20.2.11
    - urn:oid:1.2.392.100495.20.2.22
    - urn:oid:1.2.392.100495.20.2.21
    - urn:oid:1.2.392.100495.20.2.42
    - urn:oid:1.2.392.100495.20.2.61
    - urn:oid:1.2.392.100495.20.2.63
    - urn:oid:1.2.392.100495.20.2.62
    - urn:oid:1.2.392.100495.20.2.12
    - urn:oid:1.2.392.100495.20.2.41
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jami-ePreDispenseInstruction
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jami-ePreOrderUsageCode
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-gs1-14
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-hot9
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/jp-drugCode-yj
    - http://jpfhir.jp/fhir/ePrescription/ValueSet/mhlw-drugCode-generalNameCode
    - http://jpfhir.jp/fhir/Common/ValueSet/mhlw-ePreCDA-insuranceCategory
