  
#!/bin_bash
#find sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles -type f -name '*.fsh' -exec echo {} \;
#find sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles -type f -name '*.fsh' -exec sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' {} \;
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/extension/JP_eCS_OrgDept.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/extension/JP_eCS_DignosticType.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_FamilyMemberHistory_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/DummyJPCoreResources.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_Coverage_eCS_publicPayment.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_CarePlan_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_Organization_eCS_department.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_PractitionerRole_eCS_author.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_Organization_eCS_coveragePayer.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_Coverage_eCS_insurance.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS/JP_Practitioner_eCS_author.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Organization_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_MedicationDosage_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_MedicationRequest_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Encounter_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Condition_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_AllergyIntolerance_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Obs_Lab_eCS_v153.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Practitioner_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/eCS-noCLINS/JP_Patient_eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/RuleSet_short_definition.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Bundle_eReferral.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Bundle.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Bundle_ePatientCareSummary.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Composition_eReferral.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Composition_eDisSummary.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Composition_ePatientCareSummary.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Bundle_eDisSummary.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/CLINS/JP_Bundle_CLINS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/profiles/RuleSet_laboSlicing_forJLAC.fsh
echo '---1'
#find sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances -type f -name '*.fsh' -exec echo {} \;
#find sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances -type f -name '*.fsh' -exec sed -i '' -e 's/x.x.x-instance/${{ env.release_version }}/g' {} \;
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/phReferralExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/ErrorExample-JP-MedReq-PO-SID-28days.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/ErrorExample-JP-MedReq-ExtEye-Total1.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-SID-90-AMB.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-ExtAnus-AsNeeded-Total1.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-ExtSkin-Total2.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-TID-2days-dummyUsageCode.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-Fumin-asNeeded-4.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-4timez-7days.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-SID-2d.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-SID-28days.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-TID-2days.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-BID-10days-AsNeeded.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/MedicationRequest/Example-JP-MedReq-PO-AsNeeded-LimitMax.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpObsCommonExample01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpMedReq_exFkinto.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpMedReqFukintoExample01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jppatientExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-Practitioner-eCS-PCS-Author-Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-Organizaion-eCS-withDeptInfo.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-AllergyIntolerance-eCS-02.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/referralFromExample01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/phReferralExampleInline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/purposeReferralExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-Condition-eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jppatientExample1Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-Encounter-eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/piReferralExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-CarePlan-eCS-HT.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example_Patient_standard.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpComposition_eReferral_Example01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/purposeReferralExampleInline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/piReferralExampleInline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-Patient-eCS.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/cc1ReferralExampleInline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jppatientExample2Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/ccourseReferralExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/cc1ReferralExample.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpComposition_ePCS_Example01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/referralFromExample01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Observation_Labo/Example-ObsLabo-K.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Observation_Labo/Example-ObsLabo-eGFR.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Observation_Labo/Example-ObsLabo-Alb.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/referralToExample01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/ErrorExample-ObsLabo-eGFR.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpObsCommonExample01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/ccourseReferralExampleInline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-AllergyIntolerance-eCS-01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/Example-Bundle-CLINS-Referral-01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/Example-Bundle-CLINS-Referral-01noEntry.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/InlineExample-ObsLabo-CLINS-K.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/InlineExample_Patient_CLINS-standard.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/InlineExample-ObsLabo-CLINS-Alb.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/Example-Bundle-CLINS-Observation-01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/InlineExample-ObsLabo-CLINS-eGFR.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/InlineExample-ObsLabo-CLINS-UTP.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Bundle/Example-Bundle-CLINS-PCS-01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-Contained.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpMedReq_ePreExample01Inline.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/Example-JP-AllergyIntolerance-eCS-03.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpComposition_eReferral_Example01Inline_noEntry.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpMedReq_ePreExample01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/referralToExample01.fsh
sed -i '' -e 's/x.x.x-profile/${{ env.release_version }}/g' input/fsh/instances/jpAllergy_eReferral_Example01.fsh

echo '==='
