name: Ohe-build
on:
  push:
    branches: 
      - ePCS-integrated
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - 'custom-template/**'
      - '.github/workflows/main.yml'
      - 'script/*.py'
  pull_request:
    branches: [ ePCS-integrated ]
  repository_dispatch:
    types: [update]
env:
  release_version : 1.3.0-rc1
jobs:
  turn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    environment: SSH_PORT_JPFHIR  # JAMI WG アップロードサイトに関するアクセス情報の環境名
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
        submodules: true

    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi
         
    - name: Install Jekyll
      run: |
        sudo apt-get install ruby-full build-essential zlib1g-dev
        echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        sudo gem install jekyll bundler

    - name: Download IG Publisher 1.6.11
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: '1.6.11'
        path: .
        file: publisher.jar

    - name: Download validator_cli_6.1.8.jar
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: hapifhir/org.hl7.fhir.core
        tag: 'latest'
        path: .
        file: validator_cli.jar

    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile1
      with:
        url: "https://jpfhir.jp/fhir/fhir_dotFHIR_packages.tgz"
        target: .
  
    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile2
      with:
        url: "https://jpfhir.jp/fhir/core/terminology/jpfhir-terminology.r4-1.1.1.tgz"
        target: .    
    
    - name: Prepare for using all dependent packages including Jp modified version of hl7.fhir.r4.core Package 
      env:
        JPPACKAGECOREtgz: fhir_dotFHIR_packages.tgz
        JPTerminologyCOREdir: jpfhir-terminology.r4#1.1.1
        JPTerminologyCOREPtgz: jpfhir-terminology.r4-1.1.1.tgz
        JPCOREtgzjp: jp-core.r4-1.1.2.tgz
        JPCOREdir: jp-core.r4#1.1.2
      run: |
        ls -l .
        pwd
        echo '--1-'
        mkdir -p /home/runner/.fhir
        mv $JPPACKAGECOREtgz /home/runner/.fhir/
        mkdir -p /home/runner/.fhir/work
        mv $JPTerminologyCOREPtgz /home/runner/.fhir/work/$JPTerminologyCOREPtgz
        cd /home/runner/.fhir
        tar xzf $JPPACKAGECOREtgz
        cd /home/runner/.fhir/work
        tar xzf $JPTerminologyCOREPtgz
        cd /home/runner/.fhir
        mkdir -p packages/$JPTerminologyCOREdir
        mv /home/runner/.fhir/work/package /home/runner/.fhir/packages/$JPTerminologyCOREdir
        mv /home/runner/work/clinical-core/clinical-core/packages_snapshot/$JPCOREtgzjp /home/runner/.fhir/work/
        cd /home/runner/.fhir/work
        tar xzf $JPCOREtgzjp
        mkdir -p /home/runner/.fhir/packages/$JPCOREdir
        ls -l /home/runner/.fhir/packages/
        mv /home/runner/.fhir/work/package /home/runner/.fhir/packages/$JPCOREdir/

    - name: apply the version of sushi-config.yaml
      run: |
        sed 's/version: 1.2.0-temp/version: ${{ env.release_version }}/g' sushi-config.yaml > sushi-config-temp.yaml
        mv sushi-config-temp.yaml sushi-config.yaml
        cd forPackageRelease
        sed 's/1.2.0-temp/${{ env.release_version }}/g' package-diff.json >package-diff-temp.json
        sed 's/1.2.0-temp/${{ env.release_version }}/g' package-snap.json >package-snap-temp.json
        mv package-diff-temp.json package-diff.json
        mv package-snap-temp.json package-snap.json
        cd ..

    - name: Run IG Publisher
      run: | 
        mkdir -p input-cache
        mv ./publisher.jar ./input-cache
        unset DISPLAY
        java -Xmx4G -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini  -tx n/a

    - name: replace url of html files referring simplifier.net package
      run:  |
        : # https://simplifier.net/resolve?scope=jp-core.r4@1.1.1-snap&amp;canonical=http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Common"
        : #   ↓
        : # https://jpfhir.jp/fhir/core/1.1.1/StructureDefinition-jp-observation-common.html
        : # https://simplifier.net/resolve?canonical=http%3A%2F%2Fjpfhir.jp%2Ffhir%2Fcore%2FValueSet%2FJP_MedicationSubstitutionNotAllowedReason_VS&scope=jpfhir-terminology@1.1.1
        cd output
        for file in *.html
        do
          python ../script/replaceUrls.py $file >$file".2.html"
          cp $file".2.html" $file
        done
        cd ..
    - name: prepare gtz files for upload to remote site
      run: | 
        tar czf output.tgz output

    - name:  create differential package 
      run: | 
        cd fsh-generated
        mkdir -p package
        cp resources/StructureDefinition-* package/
        cp resources/ValueSet-* package/
        cp resources/CodeSystem-* package/
        cp resources/ImplementationGuide-* package/
        cp resources/NamingSystem-* package/
        cp ../forPackageRelease/package-diff.json package/package.json
        tar czf jp-clins-package-diff.tgz package
        cp jp-clins-package-diff.tgz ../forPackageRelease/jp-clins.r4-${{ env.release_version }}.tgz
  
    - name: validate
      run: |
        java -Xmx4G -Djava.awt.headless=true -jar validator_cli.jar fsh-generated/resources/Bundle-Bundle-CLINS-*.json -display-issues-are-warnings -version 4.0.1 -locale ja-JP -ig jp-core.r4#1.1.2 -ig jpfhir-terminology.r4#1.1.1 -ig  fsh-generated/jp-clins-package-diff.tgz -tx n/a  -language ja

    - name: generate snapshot package using sushi -s command       
      run: |
        rm -rf fsh-generated
        sushi -s .
        mv fsh-generated fsh-generated-snap
        mkdir -p forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/StructureDefinition-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/ValueSet-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/CodeSystem-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/ImplementationGuide-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/NamingSystem-* forPackageRelease/snapshot/package/
        cp forPackageRelease/package-snap.json forPackageRelease/snapshot/package/package.json
        cd forPackageRelease/snapshot
        tar czf jp-clins-package-snap.tgz package
        cd ..
        cp snapshot/jp-clins-package-snap.tgz jp-clins.r4-${{ env.release_version }}-snap.tgz
        cd ..

    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key; ls -l key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}

    - name: rsync remote-site-deploy
      run: |
        rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_JPFHIR }}" --delete output.tgz  forPackageRelease/jp-clins.r4-${{ env.release_version }}.tgz forPackageRelease/jp-clins.r4-${{ env.release_version }}-snap.tgz ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}:${{ secrets.JAMIWG_WEBPATH }}/jpfhir.jp/fhir/clins/ --exclude .htaccess
        ssh -i key  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -p ${{ secrets.SSH_PORT_JPFHIR }} ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}   'cd ${{ secrets.JAMIWG_WEBPATH }}/jpfhir.jp/fhir/clins/ ; tar xzf output.tgz'
