name: main-yaml
on:
  push:
    branches: 
      - 1.12.0-featureRefRangeComparator
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - 'custom-template/**'
      - '.github/workflows/main.yml'
      - 'script/*.py'
  pull_request:
    branches: [ 1.12.0-featureRefRangeComparator ]
  repository_dispatch:
    types: [update]
env:
  release_version : 1.12.0-RefTest
  version_date : 
defaults:
  run:
    shell: bash # ワークフローで使うシェルをまとめて指定
jobs:
  turn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    environment: SSH_PORT_JPFHIR  # JAMI WG アップロードサイトに関するアクセス情報の環境名
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
        submodules: true
    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi
         
    - name: Install Jekyll
      run: |
        sudo apt-get install ruby-full build-essential zlib1g-dev
        echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        sudo gem install jekyll bundler

    - name: Download IG Publisher latest (not 1.6.11)
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: 'latest'
        path: .
        file: publisher.jar
    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile1
      with:
        url: "https://jpfhir.jp/fhir/fhir_dotFHIR_packages.tgz"
        target: .
          
    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile2
      with:
        url: "https://jpfhir.jp/fhir/core/terminology/jpfhir-terminology.r4-2.0.0-test.tgz"
        target: .
    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile3
      with:
        url: "https://jpfhir.jp/fhir/core/1.1.2-clins/jp-core.r4-1.1.2-clins-snap.tgz"
        target: .

    - name: Prepare for using all dependent packages including Jp modified version of hl7.fhir.r4.core Package 
      env:
        JPPACKAGECOREtgz: fhir_dotFHIR_packages.tgz
        JPTerminologyCOREdir: jpfhir-terminology.r4#2.0.0
        JPTerminologyCOREPtgz: jpfhir-terminology.r4-2.0.0-test.tgz
        JPCOREtgzjp: jp-core.r4-1.1.2-clins-snap.tgz
        JPCOREdir: jp-core.r4#1.1.2-clins
      run: |
        ls -l .
        pwd
        echo '--1-'
        : # 
        mkdir -p packages
        mkdir -p packages/$JPTerminologyCOREdir
        mkdir -p packages/$JPCOREdir
        tar $JPTerminologyCOREPtgz packages/$JPTerminologyCOREdir
        tar $JPCOREtgzjp packages/$JPCOREdir
        : #   
        mkdir -p /home/runner/.fhir
        mv $JPPACKAGECOREtgz /home/runner/.fhir/
        mkdir -p /home/runner/.fhir/work
        mv $JPTerminologyCOREPtgz /home/runner/.fhir/work/$JPTerminologyCOREPtgz
        mv $JPCOREtgzjp /home/runner/.fhir/work/
        cd /home/runner/.fhir
        tar xzf $JPPACKAGECOREtgz
        cd /home/runner/.fhir/work
        tar xzf $JPTerminologyCOREPtgz
        cd /home/runner/.fhir
        mkdir -p packages/$JPTerminologyCOREdir
        mv /home/runner/.fhir/work/package /home/runner/.fhir/packages/$JPTerminologyCOREdir
        cd /home/runner/.fhir/work
        tar xzf $JPCOREtgzjp
        mkdir -p /home/runner/.fhir/packages/$JPCOREdir
        ls -l /home/runner/.fhir/packages/
        mv /home/runner/.fhir/work/package /home/runner/.fhir/packages/$JPCOREdir/


    - name: Set current datetime
      run: echo "CURRENT_DATETIME=$(date '+%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

    - name: Use datetime in a script
      run: echo "The current datetime is ${{ env.CURRENT_DATETIME }}"

    - name: replace head-caution to dummy
      run: |
        cp custom-template/includes/head-caution-dev-dummy custom-template/includes/head-caution-dev.html

    - name: apply the version of sushi-config.yaml
      run: |
        find input/fsh/profiles -type f -name '*.fsh' -exec sed -ibak "s/x.x.x-profile/${{ env.release_version }}/g" {} \;
        find input/fsh/instances -type f -name '*.fsh' -exec sed -ibak "s/x.x.x-instance/${{ env.release_version }}/g" {} \;

        sed 's/1.x.x-temp/${{ env.release_version }}/g' sushi-config.yaml > sushi-config-temp.yaml
        sed -i 's/@buildDateXXX-temp/${{ env.version_date }}/g' sushi-config-temp.yaml
        mv sushi-config-temp.yaml sushi-config.yaml
        
        sed 's/.r4-1.x.x-temp/.r4-${{ env.release_version }}/g' input/pagecontent/validationGuide.md > input/pagecontent/validationGuide-temp.md
        sed -i 's/@buildDateXXX-temp/${{ env.version_date }}/g' input/pagecontent/validationGuide-temp.md
        mv input/pagecontent/validationGuide-temp.md input/pagecontent/validationGuide.md

        sed 's/.r4-1.x.x-temp/.r4-${{ env.release_version }}/g' input/pagecontent/index.md > input/pagecontent/index-temp.md
        mv input/pagecontent/index-temp.md input/pagecontent/index.md

        cd forPackageRelease
        sed 's/1.x.x-temp/${{ env.release_version }}/g' package-diff.json >package-diff-temp.json
        sed 's/1.x.x-temp/${{ env.release_version }}/g' package-snap.json >package-snap-temp.json
        sed 's/"description": "/"description": "${{ env.CURRENT_DATETIME }}UTC_/g' package-diff-temp.json > package-diff-temp2.json
        sed 's/"description": "/"description": "${{ env.CURRENT_DATETIME }}UTC_/g' package-snap-temp.json > package-snap-temp2.json
        mv package-diff-temp2.json package-diff.json
        mv package-snap-temp2.json package-snap.json
        cd ..

    - name: Run sushi and IG Publisher
      run: | 
        mkdir -p input-cache
        mv ./publisher.jar ./input-cache
        unset DISPLAY
        sushi .
        : # CodeSystem-v3-ActCode.jsonはFSHから変換するのではなくJSONを直接コピーする。
        : # Ccp v3ActJSON/CodeSystem-v3-ActCode.json  fsh-generated/resources/CodeSystem-v3-ActCode.json
        echo 'jpfhir-terminology.r4#2.0.0'
        cat '/home/runner/.fhir/packages/jpfhir-terminology.r4#2.0.0/package/package.json'
        echo 'jp-core.r4#1.1.2-clins'
        cat '/home/runner/.fhir/packages/jp-core.r4#1.1.2-clins/package/package.json'
        java -Xmx12G -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini  -tx n/a -language "ja" 

    - name: replace url of html files referring simplifier.net package
      run:  |
        : # https://simplifier.net/resolve?scope=jp-core.r4@1.1.1-snap&amp;canonical=http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Common"
        : #   ↓
        : # https://jpfhir.jp/fhir/core/1.1.1/StructureDefinition-jp-observation-common.html
        : # https://simplifier.net/resolve?canonical=http%3A%2F%2Fjpfhir.jp%2Ffhir%2Fcore%2FValueSet%2FJP_MedicationSubstitutionNotAllowedReason_VS&scope=jpfhir-terminology@1.1.1
        cd output
        for file in *.html
        do
          python ../script/replaceUrls.py $file >$file".2.html"
          cp $file".2.html" $file
        done
        cd ..
    - name: prepare gtz files for upload to remote site
      run: | 
        ruby ./script/create_symbolic_link_from_file2url.rb
        : # 上記rubyにより、sushi_configのspecial_URLブロックに出力されるの同じテキストが作成され、各行にln -sコマンドとしてmakeSymbolicLink.bashファイルに出力される。
        cat makeSymbolicLink.bash
        echo "cat makeSymbolicLink.bash completed"
        cd output
        echo "cd output completed"
        source ../makeSymbolicLink.bash
        echo "source ../makeSymbolicLink.bash completed"
        cd ..
        : # 
        tar czf output.tgz output
    - name:  create differential package 
      run: | 
        cd fsh-generated
        mkdir -p package
        cp resources/StructureDefinition-* package/
        cp resources/ValueSet-* package/
        cp resources/CodeSystem-* package/
        cp resources/ImplementationGuide-* package/
        cp resources/NamingSystem-* package/
        cp ../forPackageRelease/package-diff.json package/package.json
        tar czf jp-eCSCLINS-package-diff.tgz package
        cp jp-eCSCLINS-package-diff.tgz ../forPackageRelease/jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}.tgz
  
    - name: backup the generated files
      run: |
        cp -r fsh-generated fsh-generated-backup

    - name: generate snapshot package using sushi -s command       
      run: |
        rm -rf fsh-generated
        sushi -s .
        mv fsh-generated fsh-generated-snap
        mkdir -p forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/StructureDefinition-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/ValueSet-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/CodeSystem-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/ImplementationGuide-* forPackageRelease/snapshot/package/
        cp fsh-generated-snap/resources/NamingSystem-* forPackageRelease/snapshot/package/
        cp forPackageRelease/package-snap.json forPackageRelease/snapshot/package/package.json
        cd forPackageRelease/snapshot
        tar czf jp-eCSCLINS-package-snap.tgz package
        cd ..
        cp snapshot/jp-eCSCLINS-package-snap.tgz jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}-snap.tgz
        cd ..

    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key; ls -l key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}

    - name: rsync remote-site-deploy
      run: |
        rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_JPFHIR }}" --delete output.tgz  forPackageRelease/jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}.tgz forPackageRelease/jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}-snap.tgz ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}:${{ secrets.JAMIWG_WEBPATH }}/jpfhir.jp/fhir/clins/ --exclude .htaccess
        ssh -i key  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -p ${{ secrets.SSH_PORT_JPFHIR }} ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}   'cd ${{ secrets.JAMIWG_WEBPATH }}/jpfhir.jp/fhir/clins/ ; tar xzf output.tgz; rm -rf igv${{ env.release_version }}${{ env.version_date }}; mv output igv${{ env.release_version }}${{ env.version_date }}'

    - name: copy IG and Pkg to history folders
      run: |
        ssh -i key  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -p ${{ secrets.SSH_PORT_JPFHIR }} ${{ secrets.JAMIWG_USERID_AT_WEBHOST }}   'cd ${{ secrets.JAMIWG_WEBPATH }}/jpfhir.jp/fhir/clins/ ; mkdir -p ighistory/igv${{ env.release_version }}${{ env.version_date }}; rm -rf ighistory/igv${{ env.release_version }}${{ env.version_date }}; cp -r output ighistory/igv${{ env.release_version }}${{ env.version_date }}; cp jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}.tgz pkghistory/jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}.tgz; cp jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}-snap.tgz pkghistory/jp-eCSCLINS.r4-${{ env.release_version }}${{ env.version_date }}-snap.tgz;'

